# Generated by Django 5.1.4 on 2024-12-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='product',
            name='how_to_use',
        ),
    ]
