# Generated by Django 5.1.4 on 2024-12-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_product_benefits_remove_product_how_to_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='precaution',
        ),
    ]
