# Generated by Django 5.1.4 on 2024-12-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(null=True, to='myapp.category'),
        ),
    ]
