# Generated by Django 5.1.4 on 2024-12-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='raw_categories',
            field=models.TextField(blank=True),
        ),
    ]
